import type {
    Appointment,
    Business,
    Challenge,
    ChallengeEntry,
    Client,
    ContractSignature,
    Invoice,
    LoyaltyEvent,
    LoyaltyTierInfo,
    Milestone,
    MonthlyRevenue,
    Product,
    ProgressPhoto,
    Proposal,
    RecurringInvoice,
    ReferralCode,
    Resource,
    SessionTypeMapping,
    TodayStats,
    TrainingLocation,
    Transaction,
    TrialSession,
} from "./types";

export const business: Business = {
    name: "Sipho Dlamini | Personal Training",
    location: "Cape Town, South Africa",
    owner: "Sipho Dlamini",
    plan: "Pro",
    members: 24,
    activePTs: 1,
};

export const todayStats: TodayStats = {
    sessionsToday: 6,
    newMembersThisWeek: 3,
    revenueToday: 1850,
    activeMembers: 24,
    monthlyRecurringRevenue: 18500,
    upcomingSessionsNext7Days: 28,
};

export const clients: Client[] = [
    {
        id: "c1",
        name: "Thando Mbeki",
        initials: "TM",
        avatarUrl: "/christian-buehner-DItYlc26zVI-unsplash.jpg",
        email: "thando.mbeki@gmail.com",
        phone: "+27 82 345 6789",
        membershipType: "Monthly",
        membershipStatus: "Active",
        loyaltyPoints: 2800,
        loyaltyTier: "Gold",
        joinDate: "2023-06-10",
        lastVisit: "2025-04-18",
        totalSpend: 18200,
        upcomingSession: "2025-04-19 06:00",
        assignedTrainer: null,
        goals: ["Build muscle mass", "Improve cardio endurance"],
        notes: "Prefers early morning sessions. Works in the CBD — needs to finish by 7am.",
    },
    {
        id: "c2",
        name: "Zanele Jacobs",
        initials: "ZJ",
        avatarUrl: "/compagnons-a19OVaa2rzA-unsplash.jpg",
        email: "zanele.j@outlook.com",
        phone: "+27 71 234 5678",
        membershipType: "PT Package",
        membershipStatus: "Active",
        loyaltyPoints: 1950,
        loyaltyTier: "Gold",
        joinDate: "2023-09-15",
        lastVisit: "2025-04-17",
        totalSpend: 15800,
        upcomingSession: "2025-04-19 08:00",
        assignedTrainer: null,
        goals: ["Weight loss", "Tone up for wedding"],
        notes: "Getting married in August. Highly motivated. Loves HIIT.",
    },
    {
        id: "c3",
        name: "Pieter Cloete",
        initials: "PC",
        avatarUrl: "/compagnons-jzz_3jWMzHA-unsplash.jpg",
        email: "pieter.cloete@gmail.com",
        phone: "+27 83 456 7890",
        membershipType: "PT Package",
        membershipStatus: "Active",
        loyaltyPoints: 1100,
        loyaltyTier: "Silver",
        joinDate: "2024-01-20",
        lastVisit: "2025-04-16",
        totalSpend: 12400,
        upcomingSession: "2025-04-20 09:00",
        assignedTrainer: null,
        goals: ["Strength training", "Back pain management"],
        notes: "Desk job — lower back issues. Focus on posterior chain and mobility.",
    },
    {
        id: "c4",
        name: "Nomsa Khumalo",
        initials: "NK",
        avatarUrl: "/gift-habeshaw-KBv5dEN3QtY-unsplash.jpg",
        email: "nomsa.k@yahoo.com",
        phone: "+27 76 567 8901",
        membershipType: "Monthly",
        membershipStatus: "Expiring Soon",
        loyaltyPoints: 420,
        loyaltyTier: "Bronze",
        joinDate: "2024-07-05",
        lastVisit: "2025-04-10",
        totalSpend: 4800,
        upcomingSession: null,
        assignedTrainer: null,
        goals: ["General fitness", "Stress relief"],
        notes: "Membership expiring in 5 days. Send renewal reminder.",
    },
    {
        id: "c5",
        name: "Craig Williams",
        initials: "CW",
        avatarUrl: "/hiki-app-3egFJhKIThQ-unsplash.jpg",
        email: "craig.w@icloud.com",
        phone: "+27 84 678 9012",
        membershipType: "Monthly",
        membershipStatus: "Active",
        loyaltyPoints: 2400,
        loyaltyTier: "Gold",
        joinDate: "2023-04-12",
        lastVisit: "2025-04-18",
        totalSpend: 22500,
        upcomingSession: "2025-04-19 07:00",
        assignedTrainer: null,
        goals: ["Marathon training", "Flexibility"],
        notes: "Training for Two Oceans Ultra. Endurance-focused programme.",
    },
    {
        id: "c6",
        name: "Ayanda Ngcobo",
        initials: "AN",
        avatarUrl: "/jake-nackos-IF9TK5Uy-KI-unsplash.jpg",
        email: "ayanda.n@gmail.com",
        phone: "+27 72 789 0123",
        membershipType: "PT Package",
        membershipStatus: "Active",
        loyaltyPoints: 1620,
        loyaltyTier: "Gold",
        joinDate: "2024-02-28",
        lastVisit: "2025-04-17",
        totalSpend: 14200,
        upcomingSession: "2025-04-19 10:00",
        assignedTrainer: null,
        goals: ["Post-natal fitness", "Core strength"],
        notes: "Baby is 6 months old. Focus on gentle core rebuilding and pelvic floor.",
    },
    {
        id: "c7",
        name: "Liam September",
        initials: "LS",
        avatarUrl: "/jorik-kleen-lNNHyRbmm0o-unsplash.jpg",
        email: "liam.sept@hotmail.com",
        phone: "+27 81 890 1234",
        membershipType: "Monthly",
        membershipStatus: "Active",
        loyaltyPoints: 780,
        loyaltyTier: "Silver",
        joinDate: "2024-08-15",
        lastVisit: "2025-04-15",
        totalSpend: 7600,
        upcomingSession: "2025-04-21 17:00",
        assignedTrainer: null,
        goals: ["Boxing fitness", "Self-defence"],
        notes: "Enjoys boxing conditioning. Considering upgrading to PT package.",
    },
    {
        id: "c8",
        name: "Annelize van Wyk",
        initials: "AW",
        avatarUrl: "/joseph-gonzalez-iFgRcqHznqg-unsplash.jpg",
        email: "annelize.vw@gmail.com",
        phone: "+27 79 901 2345",
        membershipType: "PT Package",
        membershipStatus: "Active",
        loyaltyPoints: 3200,
        loyaltyTier: "Platinum",
        joinDate: "2022-10-01",
        lastVisit: "2025-04-18",
        totalSpend: 25000,
        upcomingSession: "2025-04-19 09:00",
        assignedTrainer: null,
        goals: ["Yoga flexibility", "Mindfulness"],
        notes: "Long-term client. Attends yoga and PT. Very consistent.",
    },
    {
        id: "c9",
        name: "Bongani Mthethwa",
        initials: "BM",
        avatarUrl: "/jurica-koletic-7YVZYZeITc8-unsplash.jpg",
        email: "bongani.m@gmail.com",
        phone: "+27 73 012 3456",
        membershipType: "Drop-in",
        membershipStatus: "Active",
        loyaltyPoints: 210,
        loyaltyTier: "Bronze",
        joinDate: "2025-01-20",
        lastVisit: "2025-04-12",
        totalSpend: 2400,
        upcomingSession: null,
        assignedTrainer: null,
        goals: ["Try different training styles"],
        notes: "Drop-in client. Comes for group sessions mostly. Considering monthly.",
    },
    {
        id: "c10",
        name: "Fatima Davids",
        initials: "FD",
        avatarUrl: "/madison-lavern-4gcqRf3-f2I-unsplash.jpg",
        email: "fatima.d@outlook.com",
        phone: "+27 82 123 4567",
        membershipType: "Monthly",
        membershipStatus: "Lapsed",
        loyaltyPoints: 350,
        loyaltyTier: "Bronze",
        joinDate: "2024-05-18",
        lastVisit: "2025-03-01",
        totalSpend: 5200,
        upcomingSession: null,
        assignedTrainer: null,
        goals: ["Weight loss", "Improve flexibility"],
        notes: "Hasn't been in 7 weeks. Follow up required — was making great progress.",
    },
    {
        id: "c11",
        name: "Ryan Abrahams",
        initials: "RA",
        avatarUrl: "/mario-la-pergola-iEpOxUNAjbo-unsplash.jpg",
        email: "ryan.a@gmail.com",
        phone: "+27 84 234 5678",
        membershipType: "PT Package",
        membershipStatus: "Active",
        loyaltyPoints: 1250,
        loyaltyTier: "Silver",
        joinDate: "2024-06-10",
        lastVisit: "2025-04-17",
        totalSpend: 11800,
        upcomingSession: "2025-04-20 07:00",
        assignedTrainer: null,
        goals: ["Bodybuilding", "Competition prep"],
        notes: "Prepping for local physique show in July. Strict diet plan.",
    },
    {
        id: "c12",
        name: "Lerato Moloi",
        initials: "LM",
        avatarUrl: "/michael-dam-mEZ3PoFGs_k-unsplash.jpg",
        email: "lerato.moloi@gmail.com",
        phone: "+27 71 345 6789",
        membershipType: "Monthly",
        membershipStatus: "Expiring Soon",
        loyaltyPoints: 510,
        loyaltyTier: "Silver",
        joinDate: "2024-10-01",
        lastVisit: "2025-04-14",
        totalSpend: 6200,
        upcomingSession: "2025-04-22 18:00",
        assignedTrainer: null,
        goals: ["HIIT fitness", "Endurance"],
        notes: "Membership expires next week. Very consistent with group sessions.",
    },
    {
        id: "c13",
        name: "Tariq Isaacs",
        initials: "TI",
        avatarUrl: "/podmatch-CgCH4V4cNGk-unsplash.jpg",
        email: "tariq.i@gmail.com",
        phone: "+27 82 456 7891",
        membershipType: "PT Package",
        membershipStatus: "Active",
        loyaltyPoints: 890,
        loyaltyTier: "Silver",
        joinDate: "2024-04-22",
        lastVisit: "2025-04-18",
        totalSpend: 9800,
        upcomingSession: "2025-04-21 06:00",
        assignedTrainer: null,
        goals: ["Functional fitness", "Injury prevention"],
        notes: "Surfer — needs rotational strength and shoulder stability.",
    },
    {
        id: "c14",
        name: "Precious Dube",
        initials: "PD",
        avatarUrl: "/samuel-raita-RiDxDgHg7pw-unsplash.jpg",
        email: "precious.d@yahoo.com",
        phone: "+27 76 567 8902",
        membershipType: "Monthly",
        membershipStatus: "Active",
        loyaltyPoints: 1400,
        loyaltyTier: "Silver",
        joinDate: "2024-03-05",
        lastVisit: "2025-04-16",
        totalSpend: 10400,
        upcomingSession: "2025-04-22 07:00",
        assignedTrainer: null,
        goals: ["Weight management", "Build confidence"],
        notes: "Has lost 12kg since starting. Very proud of progress. Keep motivating.",
    },
    {
        id: "c15",
        name: "Michael Fourie",
        initials: "MF",
        avatarUrl: "/venrick-azcueta-17qa33WJ6zI-unsplash.jpg",
        email: "michael.f@icloud.com",
        phone: "+27 83 678 9013",
        membershipType: "Monthly",
        membershipStatus: "Active",
        loyaltyPoints: 680,
        loyaltyTier: "Silver",
        joinDate: "2024-09-20",
        lastVisit: "2025-04-15",
        totalSpend: 6800,
        upcomingSession: "2025-04-23 17:00",
        assignedTrainer: null,
        goals: ["General fitness", "Stress management"],
        notes: "High-stress corporate job. Evening sessions preferred.",
    },
    {
        id: "c16",
        name: "Sihle Ndaba",
        initials: "SN",
        avatarUrl: "/vicky-hladynets-uyaTT9u6AvI-unsplash (1).jpg",
        email: "sihle.n@gmail.com",
        phone: "+27 72 789 0124",
        membershipType: "PT Package",
        membershipStatus: "Active",
        loyaltyPoints: 3100,
        loyaltyTier: "Platinum",
        joinDate: "2023-01-15",
        lastVisit: "2025-04-18",
        totalSpend: 24200,
        upcomingSession: "2025-04-19 16:00",
        assignedTrainer: null,
        goals: ["Athletic performance", "Speed training"],
        notes: "Semi-pro rugby player. Needs explosive power and agility work.",
    },
    {
        id: "c17",
        name: "Jana Booysen",
        initials: "JB",
        avatarUrl: "/vince-veras-AJIqZDAUD7A-unsplash.jpg",
        email: "jana.b@outlook.com",
        phone: "+27 79 890 1235",
        membershipType: "Monthly",
        membershipStatus: "Active",
        loyaltyPoints: 560,
        loyaltyTier: "Silver",
        joinDate: "2024-11-10",
        lastVisit: "2025-04-17",
        totalSpend: 4600,
        upcomingSession: "2025-04-21 08:00",
        assignedTrainer: null,
        goals: ["Yoga", "Core strength"],
        notes: "New to fitness. Building foundational strength before progressing.",
    },
    {
        id: "c18",
        name: "Vuyo Pikoli",
        initials: "VP",
        avatarUrl: "/wellington-ferreira-72TE8cWKXRY-unsplash.jpg",
        email: "vuyo.p@gmail.com",
        phone: "+27 81 901 2346",
        membershipType: "Drop-in",
        membershipStatus: "Active",
        loyaltyPoints: 140,
        loyaltyTier: "Bronze",
        joinDate: "2025-02-05",
        lastVisit: "2025-04-13",
        totalSpend: 2000,
        upcomingSession: null,
        assignedTrainer: null,
        goals: ["General fitness"],
        notes: "Comes for group HIIT. Sporadic attendance — travels for work.",
    },
    {
        id: "c19",
        name: "Nadine Petersen",
        initials: "NP",
        avatarUrl: "/xavier-mouton-photographie-ry_sD0P1ZL0-unsplash.jpg",
        email: "nadine.p@gmail.com",
        phone: "+27 73 012 3457",
        membershipType: "PT Package",
        membershipStatus: "Active",
        loyaltyPoints: 1750,
        loyaltyTier: "Gold",
        joinDate: "2023-11-20",
        lastVisit: "2025-04-18",
        totalSpend: 16400,
        upcomingSession: "2025-04-19 11:00",
        assignedTrainer: null,
        goals: ["Strength training", "Bone density"],
        notes: "Doctor recommended weight training for osteoporosis prevention.",
    },
    {
        id: "c20",
        name: "Kabelo Tshabalala",
        initials: "KT",
        avatarUrl: "/gift-habeshaw-KBv5dEN3QtY-unsplash.jpg",
        email: "kabelo.t@hotmail.com",
        phone: "+27 84 123 4568",
        membershipType: "Monthly",
        membershipStatus: "Expiring Soon",
        loyaltyPoints: 460,
        loyaltyTier: "Bronze",
        joinDate: "2024-08-25",
        lastVisit: "2025-04-11",
        totalSpend: 5400,
        upcomingSession: null,
        assignedTrainer: null,
        goals: ["Lose belly fat", "Build stamina"],
        notes: "Membership expiring soon. Attendance has dropped — check in.",
    },
    {
        id: "c21",
        name: "Sarah du Toit",
        initials: "ST",
        avatarUrl: "/madison-lavern-4gcqRf3-f2I-unsplash.jpg",
        email: "sarah.dt@gmail.com",
        phone: "+27 82 234 5679",
        membershipType: "Monthly",
        membershipStatus: "Active",
        loyaltyPoints: 920,
        loyaltyTier: "Silver",
        joinDate: "2024-05-30",
        lastVisit: "2025-04-16",
        totalSpend: 8200,
        upcomingSession: "2025-04-23 08:00",
        assignedTrainer: null,
        goals: ["Toning", "Nutrition guidance"],
        notes: "Interested in nutrition consult. Vegetarian — tailor meal plan.",
    },
    {
        id: "c22",
        name: "Andile Mkhize",
        initials: "AM",
        avatarUrl: null,
        email: "andile.mk@gmail.com",
        phone: "+27 71 345 6790",
        membershipType: "PT Package",
        membershipStatus: "Active",
        loyaltyPoints: 1050,
        loyaltyTier: "Silver",
        joinDate: "2024-07-15",
        lastVisit: "2025-04-17",
        totalSpend: 10800,
        upcomingSession: "2025-04-20 16:00",
        assignedTrainer: null,
        goals: ["Muscle gain", "Improve posture"],
        notes: "University student. Budget-conscious — on 10-session package.",
    },
    {
        id: "c23",
        name: "Liesl Hendriks",
        initials: "LH",
        avatarUrl: null,
        email: "liesl.h@icloud.com",
        phone: "+27 83 456 7891",
        membershipType: "Monthly",
        membershipStatus: "Lapsed",
        loyaltyPoints: 280,
        loyaltyTier: "Bronze",
        joinDate: "2024-09-05",
        lastVisit: "2025-02-20",
        totalSpend: 3800,
        upcomingSession: null,
        assignedTrainer: null,
        goals: ["Post-injury rehab", "Regain mobility"],
        notes: "Knee surgery recovery. Was doing well. Reach out to re-engage.",
    },
    {
        id: "c24",
        name: "Zukisa Mabaso",
        initials: "ZM",
        avatarUrl: null,
        email: "zukisa.m@outlook.com",
        phone: "+27 76 567 8903",
        membershipType: "Monthly",
        membershipStatus: "Expiring Soon",
        loyaltyPoints: 490,
        loyaltyTier: "Bronze",
        joinDate: "2024-10-20",
        lastVisit: "2025-04-13",
        totalSpend: 5000,
        upcomingSession: "2025-04-24 07:00",
        assignedTrainer: null,
        goals: ["Weight loss", "Build healthy habits"],
        notes: "Membership expiring in 3 days. Has been consistent — offer renewal discount.",
    },
];

export const appointments: Appointment[] = [
    { id: "a1", clientName: "Thando Mbeki", clientInitials: "TM", clientAvatarUrl: "/christian-buehner-DItYlc26zVI-unsplash.jpg", service: "Personal Training", date: "2025-04-19", time: "06:00", duration: 60, status: "Confirmed" },
    { id: "a2", clientName: "Craig Williams", clientInitials: "CW", clientAvatarUrl: "/hiki-app-3egFJhKIThQ-unsplash.jpg", service: "Personal Training", date: "2025-04-19", time: "07:00", duration: 60, status: "Confirmed" },
    { id: "a3", clientName: "Zanele Jacobs", clientInitials: "ZJ", clientAvatarUrl: "/compagnons-a19OVaa2rzA-unsplash.jpg", service: "Personal Training", date: "2025-04-19", time: "08:00", duration: 60, status: "Confirmed" },
    { id: "a4", clientName: "Annelize van Wyk", clientInitials: "AW", clientAvatarUrl: "/joseph-gonzalez-iFgRcqHznqg-unsplash.jpg", service: "Yoga Flow", date: "2025-04-19", time: "09:00", duration: 60, status: "Confirmed" },
    { id: "a5", clientName: "Ayanda Ngcobo", clientInitials: "AN", clientAvatarUrl: "/jake-nackos-IF9TK5Uy-KI-unsplash.jpg", service: "Personal Training", date: "2025-04-19", time: "10:00", duration: 60, status: "Pending" },
    { id: "a6", clientName: "Sihle Ndaba", clientInitials: "SN", clientAvatarUrl: "/vicky-hladynets-uyaTT9u6AvI-unsplash (1).jpg", service: "Boxing Conditioning", date: "2025-04-19", time: "16:00", duration: 60, status: "Confirmed" },
    { id: "a7", clientName: "Ryan Abrahams", clientInitials: "RA", clientAvatarUrl: "/mario-la-pergola-iEpOxUNAjbo-unsplash.jpg", service: "Personal Training", date: "2025-04-20", time: "07:00", duration: 60, status: "Confirmed" },
    { id: "a8", clientName: "Pieter Cloete", clientInitials: "PC", clientAvatarUrl: "/compagnons-jzz_3jWMzHA-unsplash.jpg", service: "Personal Training", date: "2025-04-20", time: "09:00", duration: 60, status: "Confirmed" },
    { id: "a9", clientName: "Andile Mkhize", clientInitials: "AM", clientAvatarUrl: null, service: "Personal Training", date: "2025-04-20", time: "16:00", duration: 60, status: "Pending" },
    { id: "a10", clientName: "Nadine Petersen", clientInitials: "NP", clientAvatarUrl: "/xavier-mouton-photographie-ry_sD0P1ZL0-unsplash.jpg", service: "Fitness Assessment", date: "2025-04-19", time: "11:00", duration: 90, status: "Confirmed" },
    { id: "a11", clientName: "Tariq Isaacs", clientInitials: "TI", clientAvatarUrl: "/podmatch-CgCH4V4cNGk-unsplash.jpg", service: "Personal Training", date: "2025-04-21", time: "06:00", duration: 60, status: "Confirmed" },
    { id: "a12", clientName: "Jana Booysen", clientInitials: "JB", clientAvatarUrl: "/vince-veras-AJIqZDAUD7A-unsplash.jpg", service: "Yoga Flow", date: "2025-04-21", time: "08:00", duration: 60, status: "Confirmed" },
    { id: "a13", clientName: "Liam September", clientInitials: "LS", clientAvatarUrl: "/jorik-kleen-lNNHyRbmm0o-unsplash.jpg", service: "Boxing Conditioning", date: "2025-04-21", time: "17:00", duration: 60, status: "Pending" },
    { id: "a14", clientName: "Precious Dube", clientInitials: "PD", clientAvatarUrl: "/samuel-raita-RiDxDgHg7pw-unsplash.jpg", service: "Personal Training", date: "2025-04-22", time: "07:00", duration: 60, status: "Confirmed" },
    { id: "a15", clientName: "Lerato Moloi", clientInitials: "LM", clientAvatarUrl: "/michael-dam-mEZ3PoFGs_k-unsplash.jpg", service: "Group HIIT", date: "2025-04-22", time: "18:00", duration: 45, status: "Pending" },
    { id: "a16", clientName: "Sarah du Toit", clientInitials: "ST", clientAvatarUrl: "/madison-lavern-4gcqRf3-f2I-unsplash.jpg", service: "Nutrition Consult", date: "2025-04-23", time: "08:00", duration: 45, status: "Confirmed" },
    { id: "a17", clientName: "Michael Fourie", clientInitials: "MF", clientAvatarUrl: "/venrick-azcueta-17qa33WJ6zI-unsplash.jpg", service: "Personal Training", date: "2025-04-23", time: "17:00", duration: 60, status: "Confirmed" },
    { id: "a18", clientName: "Zukisa Mabaso", clientInitials: "ZM", clientAvatarUrl: null, service: "Personal Training", date: "2025-04-24", time: "07:00", duration: 60, status: "Confirmed" },
    { id: "a19", clientName: "Thando Mbeki", clientInitials: "TM", clientAvatarUrl: "/christian-buehner-DItYlc26zVI-unsplash.jpg", service: "Group HIIT", date: "2025-04-24", time: "18:00", duration: 45, status: "Pending" },
    { id: "a20", clientName: "Fatima Davids", clientInitials: "FD", clientAvatarUrl: "/madison-lavern-4gcqRf3-f2I-unsplash.jpg", service: "Fitness Assessment", date: "2025-04-25", time: "10:00", duration: 90, status: "Pending" },
];

export const monthlyRevenue: MonthlyRevenue[] = [
    { month: "May 2024", total: 14200, memberships: 4200, ptSessions: 8400, classes: 1200, retail: 400 },
    { month: "Jun 2024", total: 12800, memberships: 3800, ptSessions: 7600, classes: 1000, retail: 400 },
    { month: "Jul 2024", total: 15600, memberships: 4500, ptSessions: 9200, classes: 1400, retail: 500 },
    { month: "Aug 2024", total: 16800, memberships: 5000, ptSessions: 9800, classes: 1500, retail: 500 },
    { month: "Sep 2024", total: 15200, memberships: 4800, ptSessions: 8800, classes: 1200, retail: 400 },
    { month: "Oct 2024", total: 17400, memberships: 5200, ptSessions: 10200, classes: 1500, retail: 500 },
    { month: "Nov 2024", total: 18200, memberships: 5500, ptSessions: 10600, classes: 1600, retail: 500 },
    { month: "Dec 2024", total: 14600, memberships: 4800, ptSessions: 8000, classes: 1200, retail: 600 },
    { month: "Jan 2025", total: 21800, memberships: 6500, ptSessions: 12800, classes: 1800, retail: 700 },
    { month: "Feb 2025", total: 19600, memberships: 6000, ptSessions: 11400, classes: 1600, retail: 600 },
    { month: "Mar 2025", total: 18000, memberships: 5600, ptSessions: 10400, classes: 1500, retail: 500 },
    { month: "Apr 2025", total: 18500, memberships: 5800, ptSessions: 10800, classes: 1400, retail: 500 },
];

export const products: Product[] = [
    { id: "p1", name: "Resistance Bands Set", category: "Equipment", sku: "EQP-001", price: 249, costPrice: 120, stock: 12, reorderLevel: 5, supplier: "TotalFit" },
    { id: "p2", name: "Protein Shake 6-Pack", category: "Supplements", sku: "SUP-001", price: 180, costPrice: 95, stock: 20, reorderLevel: 8, supplier: "USN South Africa" },
    { id: "p3", name: "Foam Roller", category: "Equipment", sku: "EQP-002", price: 199, costPrice: 85, stock: 8, reorderLevel: 4, supplier: "TotalFit" },
    { id: "p4", name: "Skipping Rope", category: "Equipment", sku: "EQP-003", price: 149, costPrice: 60, stock: 10, reorderLevel: 5, supplier: "TotalFit" },
    { id: "p5", name: "Branded Water Bottle", category: "Accessories", sku: "ACC-001", price: 129, costPrice: 45, stock: 18, reorderLevel: 8, supplier: "Custom Print Co" },
    { id: "p6", name: "Wrist Wraps", category: "Accessories", sku: "ACC-002", price: 169, costPrice: 65, stock: 10, reorderLevel: 4, supplier: "TotalFit" },
    { id: "p7", name: "Pre-Workout Sachets (10-Pack)", category: "Supplements", sku: "SUP-002", price: 220, costPrice: 110, stock: 15, reorderLevel: 6, supplier: "Biogen" },
    { id: "p8", name: "Yoga Mat", category: "Equipment", sku: "EQP-004", price: 349, costPrice: 170, stock: 6, reorderLevel: 3, supplier: "Lululemon SA" },
];

export const transactions: Transaction[] = [
    { id: "t1", clientName: "Thando Mbeki", service: "Personal Training", amount: 400, paymentMethod: "Card", timestamp: "2025-04-19 07:05" },
    { id: "t2", clientName: "Zanele Jacobs", service: "Personal Training", amount: 400, paymentMethod: "EFT / Ozow", timestamp: "2025-04-19 09:00" },
    { id: "t3", clientName: "Annelize van Wyk", service: "Yoga Flow", amount: 120, paymentMethod: "SnapScan", timestamp: "2025-04-19 10:05" },
    { id: "t4", clientName: "Sihle Ndaba", service: "Resistance Bands Set", amount: 249, paymentMethod: "Card", timestamp: "2025-04-19 16:50" },
    { id: "t5", clientName: "Craig Williams", service: "10x PT Sessions Package", amount: 3500, paymentMethod: "EFT / Ozow", timestamp: "2025-04-18 07:30" },
];

export const loyaltyEvents: LoyaltyEvent[] = [
    { id: "le1", clientName: "Thando Mbeki", type: "earned", points: 40, description: "Personal Training session", timestamp: "2025-04-19 07:05" },
    { id: "le2", clientName: "Zanele Jacobs", type: "earned", points: 40, description: "Personal Training session", timestamp: "2025-04-19 09:00" },
    { id: "le3", clientName: "Craig Williams", type: "earned", points: 350, description: "Package purchase — 10x PT Sessions", timestamp: "2025-04-18 07:30" },
    { id: "le4", clientName: "Annelize van Wyk", type: "redeemed", points: 200, description: "Free yoga session redemption", timestamp: "2025-04-18 09:00" },
    { id: "le5", clientName: "Sihle Ndaba", type: "earned", points: 24, description: "Purchase — Resistance Bands Set", timestamp: "2025-04-18 16:50" },
    { id: "le6", clientName: "Nadine Petersen", type: "earned", points: 40, description: "Personal Training session", timestamp: "2025-04-17 11:00" },
    { id: "le7", clientName: "Ryan Abrahams", type: "earned", points: 100, description: "Referral bonus — new client", timestamp: "2025-04-17 12:00" },
    { id: "le8", clientName: "Lerato Moloi", type: "earned", points: 15, description: "Group HIIT attendance", timestamp: "2025-04-16 18:00" },
    { id: "le9", clientName: "Thando Mbeki", type: "redeemed", points: 500, description: "Free PT session", timestamp: "2025-04-15 06:00" },
    { id: "le10", clientName: "Liam September", type: "earned", points: 25, description: "Left a Google review", timestamp: "2025-04-14 09:30" },
];

export const loyaltyTiers: LoyaltyTierInfo[] = [
    { name: "Bronze", minPoints: 0, maxPoints: 499, memberCount: 8, color: "#F97316" },
    { name: "Silver", minPoints: 500, maxPoints: 1499, memberCount: 8, color: "#A1A1AA" },
    { name: "Gold", minPoints: 1500, maxPoints: 2999, memberCount: 6, color: "#F59E0B" },
    { name: "Platinum", minPoints: 3000, maxPoints: 99999, memberCount: 2, color: "#7C3AED" },
];

export const services = [
    { name: "Personal Training", price: 400, icon: "dumbbell" },
    { name: "Group Session (max 4)", price: 150, icon: "activity" },
    { name: "Yoga Flow", price: 120, icon: "heart" },
    { name: "Boxing Conditioning", price: 180, icon: "boxing" },
    { name: "Nutrition Consult", price: 500, icon: "clipboard" },
    { name: "Fitness Assessment", price: 350, icon: "chart" },
];

export const packages = [
    { name: "10x PT Sessions", price: 3500, originalPrice: 4000, description: "Save R500" },
    { name: "Monthly 3x/week", price: 4200, originalPrice: 4800, description: "12 sessions/month" },
    { name: "Monthly 2x/week", price: 3000, originalPrice: 3200, description: "8 sessions/month" },
    { name: "Single Session", price: 400, originalPrice: 400, description: "Pay as you go" },
];

// === Feature 1: Trial Sessions ===
export const trialSessions: TrialSession[] = [
  { id: "ts1", clientName: "Michelle du Plessis", clientInitials: "MP", date: "2025-04-10", service: "Personal Training", outcome: "converted", daysToConvert: 2 },
  { id: "ts2", clientName: "David Sithole", clientInitials: "DS", date: "2025-04-12", service: "Boxing Conditioning", outcome: "follow-up" },
  { id: "ts3", clientName: "Sarah Thompson", clientInitials: "ST", date: "2025-04-14", service: "Personal Training", outcome: "converted", daysToConvert: 3 },
  { id: "ts4", clientName: "Bongani Mthembu", clientInitials: "BM", date: "2025-04-16", service: "Fitness Assessment", outcome: "not-interested" },
  { id: "ts5", clientName: "Lindi Nkomo", clientInitials: "LN", date: "2025-04-18", service: "Nutrition Consult", outcome: "pending" },
];

// === Feature 2: Proposals ===
export const proposals: Proposal[] = [
  { id: "prop1", clientId: "c1", clientName: "Thando Mbeki", clientInitials: "TM", title: "12-Week Body Transformation", status: "accepted", tiers: [{ name: "Starter", sessions: 12, sessionType: "Personal Training", validity: "3 months", price: 4200, features: ["12 PT sessions", "Programme design", "Monthly check-in"] }, { name: "Pro", sessions: 24, sessionType: "Personal Training", validity: "3 months", price: 7200, features: ["24 PT sessions", "Programme design", "Weekly check-ins", "Nutrition plan"] }, { name: "Elite", sessions: 36, sessionType: "Personal Training", validity: "3 months", price: 9000, features: ["36 PT sessions", "Programme design", "Weekly check-ins", "Nutrition plan", "Progress photos"] }], totalValue: 7200, sentDate: "2025-03-15", expiryDate: "2025-03-22", signedDate: "2025-03-16" },
  { id: "prop2", clientId: "c3", clientName: "Pieter Cloete", clientInitials: "PC", title: "Strength Building Package", status: "sent", tiers: [{ name: "Foundation", sessions: 10, sessionType: "Personal Training", validity: "6 weeks", price: 3500, features: ["10 PT sessions", "Strength programme"] }], totalValue: 3500, sentDate: "2025-04-14", expiryDate: "2025-04-21" },
  { id: "prop3", clientId: "c5", clientName: "Craig Williams", clientInitials: "CW", title: "Boxing & Conditioning", status: "viewed", tiers: [{ name: "Standard", sessions: 8, sessionType: "Boxing Conditioning", validity: "2 months", price: 2800, features: ["8 boxing sessions", "Conditioning plan"] }, { name: "Premium", sessions: 16, sessionType: "Boxing Conditioning", validity: "2 months", price: 4800, features: ["16 boxing sessions", "Conditioning plan", "Nutrition guide"] }], totalValue: 4800, sentDate: "2025-04-12", expiryDate: "2025-04-19" },
  { id: "prop4", clientId: "c7", clientName: "Annelize van Wyk", clientInitials: "AW", title: "Yoga & Mobility Programme", status: "declined", tiers: [{ name: "Essentials", sessions: 8, sessionType: "Yoga Flow", validity: "2 months", price: 2400, features: ["8 yoga sessions", "Mobility guide"] }], totalValue: 2400, sentDate: "2025-04-01", expiryDate: "2025-04-08" },
  { id: "prop5", clientId: "c9", clientName: "Ryan Abrahams", clientInitials: "RA", title: "Complete Fitness Overhaul", status: "draft", tiers: [{ name: "Basic", sessions: 10, sessionType: "Personal Training", validity: "6 weeks", price: 3000, features: ["10 sessions"] }, { name: "Complete", sessions: 20, sessionType: "Personal Training", validity: "3 months", price: 5500, features: ["20 sessions", "Nutrition plan", "Weekly check-ins"] }], totalValue: 5500, sentDate: "", expiryDate: "" },
  { id: "prop6", clientId: "c2", clientName: "Zanele Jacobs", clientInitials: "ZJ", title: "Post-Pregnancy Recovery", status: "accepted", tiers: [{ name: "Recovery", sessions: 16, sessionType: "Personal Training", validity: "4 months", price: 5600, features: ["16 PT sessions", "Post-natal programme", "Nutrition guidance", "Weekly check-ins"] }], totalValue: 5600, sentDate: "2025-03-20", expiryDate: "2025-03-27", signedDate: "2025-03-21" },
];

// === Feature 3: Referral Codes ===
export const referralCodes: ReferralCode[] = [
  { id: "ref1", clientId: "c1", clientName: "Thando Mbeki", clientInitials: "TM", code: "THANDO10", timesShared: 8, signUps: 3, conversions: 2, pointsEarned: 200 },
  { id: "ref2", clientId: "c2", clientName: "Zanele Jacobs", clientInitials: "ZJ", code: "ZANELE15", timesShared: 5, signUps: 2, conversions: 1, pointsEarned: 100 },
  { id: "ref3", clientId: "c3", clientName: "Pieter Cloete", clientInitials: "PC", code: "PIETER22", timesShared: 12, signUps: 4, conversions: 3, pointsEarned: 300 },
  { id: "ref4", clientId: "c5", clientName: "Craig Williams", clientInitials: "CW", code: "CRAIG07", timesShared: 3, signUps: 1, conversions: 1, pointsEarned: 100 },
  { id: "ref5", clientId: "c4", clientName: "Nomsa Khumalo", clientInitials: "NK", code: "NOMSA18", timesShared: 6, signUps: 2, conversions: 1, pointsEarned: 100 },
  { id: "ref6", clientId: "c7", clientName: "Annelize van Wyk", clientInitials: "AW", code: "ANNELIZE09", timesShared: 4, signUps: 3, conversions: 2, pointsEarned: 200 },
  { id: "ref7", clientId: "c8", clientName: "Ayanda Ngcobo", clientInitials: "AN", code: "AYANDA33", timesShared: 7, signUps: 2, conversions: 1, pointsEarned: 100 },
  { id: "ref8", clientId: "c10", clientName: "Nadine Petersen", clientInitials: "NP", code: "NADINE05", timesShared: 9, signUps: 1, conversions: 1, pointsEarned: 100 },
];

// === Feature 4: Contract Signatures ===
export const contractSignatures: ContractSignature[] = [
  { id: "cs1", clientId: "c1", clientName: "Thando Mbeki", contractType: "Service Agreement", signedDate: "2025-01-12", signatureMethod: "drawn" },
  { id: "cs2", clientId: "c2", clientName: "Zanele Jacobs", contractType: "Service Agreement", signedDate: "2025-01-15", signatureMethod: "typed" },
  { id: "cs3", clientId: "c3", clientName: "Pieter Cloete", contractType: "Service Agreement", signedDate: "2025-02-01", signatureMethod: "drawn" },
  { id: "cs4", clientId: "c5", clientName: "Craig Williams", contractType: "Liability Waiver", signedDate: "2025-02-10", signatureMethod: "typed" },
  { id: "cs5", clientId: "c4", clientName: "Nomsa Khumalo", contractType: "Service Agreement", signedDate: "2025-03-01", signatureMethod: "drawn" },
];

// === Feature 5: Milestones ===
export const milestones: Milestone[] = [
  { id: "ms1", clientId: "c1", clientName: "Thando Mbeki", clientInitials: "TM", type: "workout", title: "First workout completed", description: "Completed first personal training session", date: "2025-01-12", pointsAwarded: 50, celebrated: true },
  { id: "ms2", clientId: "c1", clientName: "Thando Mbeki", clientInitials: "TM", type: "sessions", title: "10 sessions completed", description: "Reached 10 total training sessions", date: "2025-02-03", pointsAwarded: 100, celebrated: true },
  { id: "ms3", clientId: "c2", clientName: "Zanele Jacobs", clientInitials: "ZJ", type: "goal", title: "Weight goal achieved: Lost 5kg", description: "Reached target weight after 8 weeks", date: "2025-03-10", pointsAwarded: 200, celebrated: true },
  { id: "ms4", clientId: "c5", clientName: "Craig Williams", clientInitials: "CW", type: "pb", title: "Personal best: Bench Press 80kg", description: "New bench press PB of 80kg", date: "2025-02-28", pointsAwarded: 75, celebrated: false },
  { id: "ms5", clientId: "c8", clientName: "Ayanda Ngcobo", clientInitials: "AN", type: "performance", title: "5km under 25 minutes", description: "Ran 5km in 24:32", date: "2025-02-15", pointsAwarded: 150, celebrated: true },
  { id: "ms6", clientId: "c3", clientName: "Pieter Cloete", clientInitials: "PC", type: "anniversary", title: "1 month anniversary", description: "One month of consistent training", date: "2025-02-12", pointsAwarded: 50, celebrated: true },
  { id: "ms7", clientId: "c4", clientName: "Nomsa Khumalo", clientInitials: "NK", type: "sessions", title: "25 sessions completed", description: "Quarter century of sessions", date: "2025-03-15", pointsAwarded: 150, celebrated: false },
  { id: "ms8", clientId: "c7", clientName: "Annelize van Wyk", clientInitials: "AW", type: "goal", title: "Flexibility goal reached", description: "Can now touch toes without bending knees", date: "2025-03-05", pointsAwarded: 100, celebrated: true },
  { id: "ms9", clientId: "c10", clientName: "Nadine Petersen", clientInitials: "NP", type: "pb", title: "Deadlift PB: 100kg", description: "Hit triple figures on deadlift", date: "2025-04-01", pointsAwarded: 75, celebrated: false },
  { id: "ms10", clientId: "c9", clientName: "Ryan Abrahams", clientInitials: "RA", type: "workout", title: "First HIIT class", description: "Survived first Group HIIT session", date: "2025-04-05", pointsAwarded: 50, celebrated: true },
];

// === Feature 6: Challenges ===
export const challenges: Challenge[] = [
  { id: "ch1", name: "April Step Challenge", type: "competitive", metric: "Most sessions attended", startDate: "2025-04-01", endDate: "2025-04-30", participantCount: 14, status: "active" },
  { id: "ch2", name: "March Workout Warrior", type: "competitive", metric: "Most workouts completed", startDate: "2025-03-01", endDate: "2025-03-31", participantCount: 18, status: "completed", winner: "Thando Mbeki" },
  { id: "ch3", name: "February Nutrition Streak", type: "threshold", metric: "Log meals 5x per week for 4 weeks", goal: "20 logged days", startDate: "2025-02-01", endDate: "2025-02-28", participantCount: 12, status: "completed" },
];

export const challengeLeaderboard: ChallengeEntry[] = [
  { challengeId: "ch1", clientId: "c1", clientName: "Thando Mbeki", clientInitials: "TM", score: 18, rank: 1, change: 2 },
  { challengeId: "ch1", clientId: "c5", clientName: "Craig Williams", clientInitials: "CW", score: 16, rank: 2, change: 0 },
  { challengeId: "ch1", clientId: "c8", clientName: "Ayanda Ngcobo", clientInitials: "AN", score: 15, rank: 3, change: 1 },
  { challengeId: "ch1", clientId: "c3", clientName: "Pieter Cloete", clientInitials: "PC", score: 14, rank: 4, change: -1 },
  { challengeId: "ch1", clientId: "c2", clientName: "Zanele Jacobs", clientInitials: "ZJ", score: 13, rank: 5, change: 0 },
  { challengeId: "ch1", clientId: "c4", clientName: "Nomsa Khumalo", clientInitials: "NK", score: 12, rank: 6, change: 3 },
  { challengeId: "ch1", clientId: "c7", clientName: "Annelize van Wyk", clientInitials: "AW", score: 11, rank: 7, change: -2 },
  { challengeId: "ch1", clientId: "c9", clientName: "Ryan Abrahams", clientInitials: "RA", score: 10, rank: 8, change: 1 },
  { challengeId: "ch1", clientId: "c10", clientName: "Nadine Petersen", clientInitials: "NP", score: 9, rank: 9, change: -1 },
  { challengeId: "ch1", clientId: "c6", clientName: "Sihle Ndaba", clientInitials: "SN", score: 8, rank: 10, change: 0 },
  { challengeId: "ch1", clientId: "c11", clientName: "Tariq Isaacs", clientInitials: "TI", score: 7, rank: 11, change: 2 },
  { challengeId: "ch1", clientId: "c12", clientName: "Jana Booysen", clientInitials: "JB", score: 6, rank: 12, change: -1 },
  { challengeId: "ch1", clientId: "c13", clientName: "Liam September", clientInitials: "LS", score: 5, rank: 13, change: 0 },
  { challengeId: "ch1", clientId: "c14", clientName: "Precious Dube", clientInitials: "PD", score: 4, rank: 14, change: -1 },
];

// === Feature 7: Progress Photos ===
export const progressPhotos: ProgressPhoto[] = [
  { id: "pp1", clientId: "c1", date: "2025-01-12", photoUrl: "/placeholder-before.jpg", weight: 92, bodyFat: 24, popiConsent: true },
  { id: "pp2", clientId: "c1", date: "2025-02-12", photoUrl: "/placeholder-mid.jpg", weight: 89, bodyFat: 22, popiConsent: true },
  { id: "pp3", clientId: "c1", date: "2025-03-12", photoUrl: "/placeholder-after.jpg", weight: 86.5, bodyFat: 20, popiConsent: true, notes: "Great progress" },
  { id: "pp4", clientId: "c2", date: "2025-01-20", photoUrl: "/placeholder-before.jpg", weight: 68, bodyFat: 28, popiConsent: true },
  { id: "pp5", clientId: "c2", date: "2025-03-20", photoUrl: "/placeholder-after.jpg", weight: 63, bodyFat: 24, popiConsent: true },
  { id: "pp6", clientId: "c5", date: "2025-02-01", photoUrl: "/placeholder-before.jpg", weight: 85, bodyFat: 18, popiConsent: false },
  { id: "pp7", clientId: "c5", date: "2025-04-01", photoUrl: "/placeholder-after.jpg", weight: 83, bodyFat: 15, popiConsent: true },
  { id: "pp8", clientId: "c3", date: "2025-02-15", photoUrl: "/placeholder-before.jpg", weight: 95, bodyFat: 22, popiConsent: true },
  { id: "pp9", clientId: "c3", date: "2025-04-15", photoUrl: "/placeholder-after.jpg", weight: 90, bodyFat: 19, popiConsent: true },
  { id: "pp10", clientId: "c8", date: "2025-01-05", photoUrl: "/placeholder-before.jpg", weight: 72, bodyFat: 26, popiConsent: true },
  { id: "pp11", clientId: "c8", date: "2025-02-05", photoUrl: "/placeholder-mid.jpg", weight: 70, bodyFat: 24, popiConsent: true },
  { id: "pp12", clientId: "c8", date: "2025-03-05", photoUrl: "/placeholder-after.jpg", weight: 67, bodyFat: 21, popiConsent: true },
];

// === Feature 8: Training Locations ===
export const trainingLocations: TrainingLocation[] = [
  { id: "loc1", name: "Home Studio", address: "24 Kloof Street, Cape Town", sessionTypes: ["Personal Training", "Boxing Conditioning", "Fitness Assessment"], travelBuffer: 0, capacity: 2, equipment: ["Full rack", "Dumbbells", "Cables", "Bench", "Boxing bag"], notes: "Fully equipped, 2 clients max" },
  { id: "loc2", name: "Client's Home", address: "Mobile sessions", sessionTypes: ["Personal Training", "Yoga Flow", "Fitness Assessment"], travelBuffer: 30, capacity: 1, equipment: ["Resistance bands", "Mat", "Skipping rope"], notes: "Bring resistance bands, mat" },
  { id: "loc3", name: "Signal Hill Park", address: "Signal Hill Road, Cape Town", sessionTypes: ["Group HIIT", "Boxing Conditioning"], travelBuffer: 15, capacity: 8, equipment: ["Cones", "Battle ropes", "Mats"], notes: "Outdoor bootcamp location" },
];

export const sessionTypeMapping: SessionTypeMapping[] = [
  { sessionType: "Personal Training", defaultLocationId: "loc1", buffer: 0, canOverride: true },
  { sessionType: "Group HIIT", defaultLocationId: "loc3", buffer: 15, canOverride: true },
  { sessionType: "Boxing Conditioning", defaultLocationId: "loc1", buffer: 0, canOverride: true },
  { sessionType: "Nutrition Consult", defaultLocationId: "loc1", buffer: 0, canOverride: true },
  { sessionType: "Yoga Flow", defaultLocationId: "loc2", buffer: 30, canOverride: true },
];

// === Feature 10: Invoices ===
export const invoices: Invoice[] = [
  { id: "inv1", clientId: "c1", clientName: "Thando Mbeki", clientInitials: "TM", invoiceNumber: "INV-0042", description: "Monthly PT Package", lineItems: [{ description: "Personal Training x8", quantity: 8, unitPrice: 350, total: 2800 }], subtotal: 2800, vat: 420, total: 3220, dueDate: "2025-04-15", status: "paid", paidDate: "2025-04-14" },
  { id: "inv2", clientId: "c2", clientName: "Zanele Jacobs", clientInitials: "ZJ", invoiceNumber: "INV-0043", description: "Recovery Programme", lineItems: [{ description: "PT Sessions x4", quantity: 4, unitPrice: 400, total: 1600 }, { description: "Nutrition Consult", quantity: 1, unitPrice: 450, total: 450 }], subtotal: 2050, vat: 307.5, total: 2357.5, dueDate: "2025-04-20", status: "outstanding", chaseStatus: "Reminder sent" },
  { id: "inv3", clientId: "c3", clientName: "Pieter Cloete", clientInitials: "PC", invoiceNumber: "INV-0044", description: "Strength Programme", lineItems: [{ description: "PT Sessions x10", quantity: 10, unitPrice: 350, total: 3500 }], subtotal: 3500, vat: 525, total: 4025, dueDate: "2025-04-01", status: "overdue", chaseStatus: "Final notice" },
  { id: "inv4", clientId: "c5", clientName: "Craig Williams", clientInitials: "CW", invoiceNumber: "INV-0045", description: "Boxing Package", lineItems: [{ description: "Boxing Sessions x6", quantity: 6, unitPrice: 400, total: 2400 }], subtotal: 2400, vat: 360, total: 2760, dueDate: "2025-04-25", status: "outstanding", chaseStatus: "Auto-chase ON" },
  { id: "inv5", clientId: "c4", clientName: "Nomsa Khumalo", clientInitials: "NK", invoiceNumber: "INV-0046", description: "Monthly Membership", lineItems: [{ description: "Monthly Unlimited", quantity: 1, unitPrice: 2500, total: 2500 }], subtotal: 2500, vat: 375, total: 2875, dueDate: "2025-04-10", status: "paid", paidDate: "2025-04-09" },
  { id: "inv6", clientId: "c7", clientName: "Annelize van Wyk", clientInitials: "AW", invoiceNumber: "INV-0047", description: "Yoga Sessions", lineItems: [{ description: "Yoga Flow x4", quantity: 4, unitPrice: 300, total: 1200 }], subtotal: 1200, vat: 180, total: 1380, dueDate: "2025-04-18", status: "paid", paidDate: "2025-04-17" },
  { id: "inv7", clientId: "c8", clientName: "Ayanda Ngcobo", clientInitials: "AN", invoiceNumber: "INV-0048", description: "Assessment + Programme", lineItems: [{ description: "Fitness Assessment", quantity: 1, unitPrice: 500, total: 500 }, { description: "Programme Design", quantity: 1, unitPrice: 300, total: 300 }], subtotal: 800, vat: 120, total: 920, dueDate: "2025-05-01", status: "draft" },
  { id: "inv8", clientId: "c9", clientName: "Ryan Abrahams", clientInitials: "RA", invoiceNumber: "INV-0049", description: "PT Sessions", lineItems: [{ description: "PT Sessions x8", quantity: 8, unitPrice: 350, total: 2800 }], subtotal: 2800, vat: 420, total: 3220, dueDate: "2025-04-30", status: "outstanding", chaseStatus: "Auto-chase ON" },
];

export const recurringInvoices: RecurringInvoice[] = [
  { id: "ri1", clientId: "c1", clientName: "Thando Mbeki", description: "Monthly PT Package (8 sessions)", amount: 3220, frequency: "monthly", nextDate: "2025-05-15", status: "active" },
  { id: "ri2", clientId: "c4", clientName: "Nomsa Khumalo", description: "Monthly Unlimited Membership", amount: 2875, frequency: "monthly", nextDate: "2025-05-10", status: "active" },
  { id: "ri3", clientId: "c7", clientName: "Annelize van Wyk", description: "Monthly Yoga Package", amount: 1380, frequency: "monthly", nextDate: "2025-05-18", status: "paused" },
];

// === Feature 11: Resources ===
export const resources: Resource[] = [
  { id: "res1", name: "Beginner's Strength Guide", category: "Workout Guides", fileType: "pdf", fileSize: "2.4 MB", url: "#", assignedTo: "all", downloadCount: 34, dateAdded: "2025-01-05" },
  { id: "res2", name: "HIIT Workout Companion", category: "Workout Guides", fileType: "pdf", fileSize: "1.8 MB", url: "#", assignedTo: "all", downloadCount: 28, dateAdded: "2025-01-10" },
  { id: "res3", name: "Advanced Lifting Techniques", category: "Workout Guides", fileType: "video", url: "#", assignedTo: ["c1", "c3", "c5"], downloadCount: 12, dateAdded: "2025-02-15" },
  { id: "res4", name: "Home Workout Essentials", category: "Workout Guides", fileType: "pdf", fileSize: "3.1 MB", url: "#", assignedTo: "all", downloadCount: 45, dateAdded: "2025-01-20" },
  { id: "res5", name: "Nutrition Basics for Athletes", category: "Nutrition Guides", fileType: "pdf", fileSize: "4.2 MB", url: "#", assignedTo: "all", downloadCount: 52, dateAdded: "2025-01-08" },
  { id: "res6", name: "Meal Prep Guide", category: "Nutrition Guides", fileType: "pdf", fileSize: "2.1 MB", url: "#", assignedTo: "all", downloadCount: 38, dateAdded: "2025-02-01" },
  { id: "res7", name: "Supplement Guide", category: "Nutrition Guides", fileType: "pdf", fileSize: "1.5 MB", url: "#", assignedTo: "all", downloadCount: 22, dateAdded: "2025-03-01" },
  { id: "res8", name: "Welcome Pack", category: "Onboarding Documents", fileType: "pdf", fileSize: "1.2 MB", url: "#", assignedTo: "all", downloadCount: 67, dateAdded: "2025-01-01", dripDay: 1 },
  { id: "res9", name: "Training Rules & Etiquette", category: "Onboarding Documents", fileType: "pdf", fileSize: "0.8 MB", url: "#", assignedTo: "all", downloadCount: 55, dateAdded: "2025-01-01", dripDay: 1 },
  { id: "res10", name: "Goal Setting Worksheet", category: "Onboarding Documents", fileType: "pdf", fileSize: "0.5 MB", url: "#", assignedTo: "all", downloadCount: 42, dateAdded: "2025-01-15", dripDay: 3 },
  { id: "res11", name: "Foam Rolling Guide", category: "Recovery & Mobility", fileType: "video", url: "#", assignedTo: "all", downloadCount: 19, dateAdded: "2025-02-20" },
  { id: "res12", name: "Stretching Routine", category: "Recovery & Mobility", fileType: "pdf", fileSize: "1.9 MB", url: "#", assignedTo: "all", downloadCount: 31, dateAdded: "2025-02-25" },
  { id: "res13", name: "Sleep Optimisation Tips", category: "Recovery & Mobility", fileType: "pdf", fileSize: "0.7 MB", url: "#", assignedTo: "all", downloadCount: 25, dateAdded: "2025-03-10" },
  { id: "res14", name: "Recovery Day Protocols", category: "Recovery & Mobility", fileType: "pdf", fileSize: "1.3 MB", url: "#", assignedTo: "all", downloadCount: 17, dateAdded: "2025-03-15" },
  { id: "res15", name: "Client Handbook", category: "Client Handbooks", fileType: "pdf", fileSize: "3.5 MB", url: "#", assignedTo: "all", downloadCount: 61, dateAdded: "2025-01-01", dripDay: 1 },
  { id: "res16", name: "Training Log Template", category: "Client Handbooks", fileType: "pdf", fileSize: "0.4 MB", url: "#", assignedTo: "all", downloadCount: 48, dateAdded: "2025-01-05", dripDay: 7 },
  { id: "res17", name: "Progress Photo Guidelines", category: "Client Handbooks", fileType: "pdf", fileSize: "0.6 MB", url: "#", assignedTo: "all", downloadCount: 33, dateAdded: "2025-02-10" },
  { id: "res18", name: "FAQ & Policies", category: "Client Handbooks", fileType: "pdf", fileSize: "0.9 MB", url: "#", assignedTo: "all", downloadCount: 29, dateAdded: "2025-01-01" },
];
